# Generated by Django 4.1.2 on 2022-11-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='date_released',
            new_name='date_published',
        ),
    ]
